# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: elistory-backend-image

# Deploy to these servers.
servers:
  - 5.35.83.12

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: /

  # Always use an access token rather than real password when possible.
  password: /