- name: install docker
  apt:
    name: docker-compose
    state: present

- name: update repo
  git:
    repo: git@github.com:ElistoryElista/volgograd-backend.git
    dest: "/app/elistory-volgograd-backend"
    key_file: "~/.ssh/prod-deploy-key-volgograd-backend"
    version: main
    accept_hostkey: yes

- name: update docker image
  shell: docker-compose build
  args:
    chdir: "/app/elistory-volgograd-backend"

- name: stop docker-compose
  shell: pwd && docker-compose stop
  args:
    chdir: "/app/elistory-volgograd-backend"

- name: start docker-compose
  shell: docker-compose up -d
  args:
    chdir: "/app/elistory-volgograd-backend"